services:
    # manager
    shapecode_cron.cronjob_manager:
        class: Shapecode\Bundle\CronBundle\Manager\CronJobManager
        public: true
        arguments:
            - '@kernel'
            - '@annotation_reader'

    # commands
    shapecode_cron.abstract:
        abstract: true
        arguments:
            - '@kernel'
            - '@annotations.reader'
            - '@doctrine'
            - '@request_stack'

    shapecode_cron.command.cron_job_edit:
        class: Shapecode\Bundle\CronBundle\Command\CronJobEditCommand
        parent: shapecode_cron.abstract
        public: true
        tags:
            - { name: console.command }

    shapecode_cron.command.cron_process:
        class: Shapecode\Bundle\CronBundle\Command\CronProcessCommand
        parent: shapecode_cron.abstract
        public: true
        tags:
            - { name: console.command }

    shapecode_cron.command.cron_prune_logs:
        class: Shapecode\Bundle\CronBundle\Command\CronPruneLogsCommand
        parent: shapecode_cron.abstract
        public: true
        tags:
            - { name: console.command }

    shapecode_cron.command.cron_run:
        class: Shapecode\Bundle\CronBundle\Command\CronRunCommand
        parent: shapecode_cron.abstract
        public: true
        tags:
            - { name: console.command }

    shapecode_cron.command.cron_scan:
        class: Shapecode\Bundle\CronBundle\Command\CronScanCommand
        public: true
        arguments:
            - '@shapecode_cron.cronjob_manager'
            - '@kernel'
            - '@annotations.reader'
            - '@doctrine'
            - '@request_stack'
        tags:
            - { name: console.command }

    shapecode_cron.command.cron_status:
        class: Shapecode\Bundle\CronBundle\Command\CronStatusCommand
        public: true
        parent: shapecode_cron.abstract
        tags:
            - { name: console.command }

    # cronjobs
    shapecode_cron.cronjob.generic_clean_up_daily:
        class: Shapecode\Bundle\CronBundle\CronJob\GenericCleanUpDailyCommand
        public: true
        arguments:
            - '@event_dispatcher'
        tags:
            - { name: console.command }
            - { name: shapecode_cron.cron_job, expression: '@daily' }

    shapecode_cron.cronjob.generic_clean_up_hourly:
        class: Shapecode\Bundle\CronBundle\CronJob\GenericCleanUpHourlyCommand
        public: true
        arguments:
            - '@event_dispatcher'
        tags:
            - { name: console.command }
            - { name: shapecode_cron.cron_job, expression: '@hourly' }

    # eventlistener
    shapecode_cron.event_listener.entity_subscriber:
        class: Shapecode\Bundle\CronBundle\EventListener\EntitySubscriber
        tags:
            - { name: doctrine.event_subscriber }
